### ISSUE TITLE
The latest Steam Client update broke this plugin alongside other plugins. 

### ISSUE THREAD

**Issue by calvinklein97** [jfernandez/ControllerTools#46] opened 2024-05-08 13:31 UTC
The most recent steam client update (7th May) broke a few Decky plugins and this is one of them. Would be nice to get a fix for that. Thanks!

**Comment by jfernandez** [comment] 2024-05-08 14:32
Duplicate of #43

**Closed** 2024-05-08 14:32 UTC
